export const Experience = [
  {
    image: '/assets/utaustin.webp',
    width: 80,
    height: 100,
    alt: 'Logo',
    Title: 'UT-Austin',
    Role: 'Research Assistant', 
    Date: '/ August 2024 - Present',
    Description: 'Conducting research at UT, being mentored by Chandrajit Bajaj, Head of CV over artificial intelligence',
  },
  {
    image: '/assets/statoracle_logo.webp',
    width: 80,
    height: 100,
    alt: 'Logo',
    Title: 'Stat-Oracle',
    Role: 'Co-Head of Technology', 
    Date: '/ June 2024 - Present',
    Description: 'Stat-Oracle is a soccer startup where users upload game clips to be processed with AI to gain stats and insights. Developed and optimized the user interface for a machine learning database, enhancing usability and user experience. Implemented a waitlist feature using the Supabase, improving customer acquisition and retention.',
  },
  {
    image: '/assets/CortexPD.webp',
    width: 80,
    height: 100,
    alt: 'Logo',
    Title: 'CortexPD',
    Role: 'Frontend Dev', 
    Date: '/ June 2024 - Present',
    Description: 'CortexPD is a nonprofit organization dedicated to improving the lives of people diagnosed with Parkinson\'s disorder. Designed and implemented a comprehensive website, focusing on user interface and overall design to improve user engagement.',
  },
  {
    image: '/assets/AP-Visuals.png',
    width: 80,
    height: 100,
    alt: 'Logo',
    Title: 'AP-Visuals',
    Role: 'Founder', 
    Date: '/ May 2024 - Present',
    Description: 'Founded and developed a freelancing company, delivering custom visual and web solutions to a diverse range of clients. Amassed over 30$ in sale so far',
  },
]
