export const Projects = [
  {
    image: './assets/statoracle.png',
    width: 230,
    alt: 'Website_Image',
    title: 'Stat-Oracle',
    date: 'February 2024',
    description: 'A website I helped develop for Stat-Oracle, a startup based on providing data analytics for youth teams.',
    link: 'https://statoracle.org/',
    repo: '',
    Languages: ['React', 'TailwindCSS', 'Next.js',],
  },
  {
    image: './assets/AAU.png',
    width: 230,
    alt: 'Website_Image',
    title: 'AAU Fundraising',
    date: 'October 2024',
    description: 'A website I created for Angels Among Us a nonprofit organization aimed at supporting cancer patients!',
    link: 'https://aaufundraising.org/',
    repo: 'https://github.com/aadityapanchal7/AAU',
    Languages: ['React', 'TailwindCSS', 'Next.js',],
  },
  {
    image: './assets/Neuro_S.png',
    width: 230,
    alt: 'Website_Image',
    title: 'CortexPD',
    date: 'June 2024',
    description: 'A website I created for CortexPD a nonprofit organization aimed at combating Parkinsons disease!',
    link: 'https://cortexpd.vercel.app/',
    repo: 'https://github.com/aadityapanchal7/NeuroCatalyst/',
    Languages: ['React', 'TailwindCSS', 'Javascript',],
  },
  {
    image: './assets/RMA.png',
    width: 240,
    alt: 'Website_Image',
    title: 'Research Made Accessible',
    date: 'May 2024',
    description: 'A static website created for a research nonprofit. My first project which incorporates NextJS.',
    link: 'https://www.researchmadeaccessible.org',
    repo: 'https://github.com/aadityapanchal7/rma',
    Languages: ['Next.js', 'TailwindCSS', 'React',],
  },
  {
    image: './assets/Portfolio_S.png',
    width: 300,
    alt: 'Website_Image',
    title: 'This Website',
    date: 'June 2024',
    description: 'This is the first iteration of my personal portfolio, built using React, and TailwindCSS :)',
    link: 'https://aadityapanchal.vercel.app',
    repo: 'https://github.com/aadityapanchal7/portfolio-v1',
    Languages: ['React', 'TailwindCSS'],
  },
]

